# Generated by Django 2.0.4 on 2018-04-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('condition', models.IntegerField(choices=[(5, 'Joy'), (10, 'Passionate'), (15, 'Happy'), (20, 'Optimistic'), (25, 'Content'), (30, 'Bored'), (31, 'Tired'), (33, 'Hungry'), (35, 'Pessimistic'), (40, 'Frustrated'), (45, 'Overwhelmed'), (50, 'Dissapointed'), (55, 'Worried'), (60, 'Angry'), (65, 'Jealous'), (70, 'Insecure'), (75, 'Guilty'), (80, 'Fear'), (85, 'Grief'), (90, 'Despair')])),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
